# Entity record for City of Addison, TX
city_website: https://www.addisontx.gov
colors:
- '#24AAE1'
meetings_url: https://www.addisontx.gov/Government/Meetings-Agendas/Watch-City-Council-Meetings
state: TX
