# Entity record for City of Arlington, TX
city_website: https://www.arlingtontx.gov
colors:
- '#082a55'
- '#990c22'
meetings_url: https://www.arlingtontx.gov/Government/Meetings-Agendas/Watch-Meetings
state: TX
