# Entity record for City of Fort Worth, TX
city_website: https://www.fortworthtexas.gov
colors:
- '#045b9b'
- '#6294be'
meetings_url: https://www.fortworthtexas.gov/departments/communications/fwtv
state: TX
