#!/usr/bin/env python3
"""Publish one standard review manifest through the GitHub CLI.

This intentionally keeps GitHub API calls out of feature workflows.  The manifest is local,
versioned, and generated by a feature package command; all remote writes happen here.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import tempfile
from pathlib import Path

from citypods.review_issues import (
    MANAGED_LABEL,
    PublicationStatus,
    append_envelope,
    bounded_body,
    publication_summary,
)


def _gh(*args: str, input_text: str | None = None) -> str:
    result = subprocess.run(
        ["gh", *args], input=input_text, text=True, capture_output=True, check=False
    )
    if result.returncode:
        raise RuntimeError(result.stderr.strip() or "gh command failed")
    return result.stdout.strip()


def _body_file(path: Path, *, family: str, candidate_id: str, surface: str) -> Path:
    text = path.read_text(encoding="utf-8")
    text = append_envelope(text, family=family, candidate_id=candidate_id, surface=surface)
    text, _ = bounded_body(text)
    handle = tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix=".md", delete=False)
    with handle:
        handle.write(text)
    return Path(handle.name)


def _manifest_path(root: Path, value: str) -> Path:
    """Support both old package manifests (repo-relative) and new manifest-relative paths."""
    direct = Path(value)
    return direct if direct.exists() else root / direct


def _find_open(title: str, label: str) -> str:
    payload = _gh(
        "issue",
        "list",
        "--state",
        "open",
        "--label",
        label,
        "--limit",
        "500",
        "--json",
        "number,title",
    )
    rows = json.loads(payload or "[]")
    return str(next((row["number"] for row in rows if row.get("title") == title), ""))


def _upsert(title: str, label: str, body: Path) -> str:
    existing = _find_open(title, label)
    if existing:
        _gh("issue", "edit", existing, "--body-file", str(body), "--add-label", MANAGED_LABEL)
        return existing
    url = _gh(
        "issue",
        "create",
        "--title",
        title,
        "--label",
        label,
        "--label",
        MANAGED_LABEL,
        "--body-file",
        str(body),
    )
    return url.rstrip("/").split("/")[-1]


def publish(args: argparse.Namespace) -> int:
    manifest_path = Path(args.manifest)
    root = manifest_path.parent
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    children = list(manifest.get("children") or [])
    reasons = list(manifest.get("reasons") or [])
    if not children:
        status = PublicationStatus.BLOCKED if reasons else PublicationStatus.NO_CANDIDATES
        print(publication_summary(status=status, selected=0, published=0, reasons=reasons))
        return 0
    family = args.family
    label = args.label
    _gh(
        "label",
        "create",
        MANAGED_LABEL,
        "--color",
        "5319e7",
        "--force",
        "--description",
        "Bot-managed weekly review issue",
    )
    _gh(
        "label",
        "create",
        label,
        "--color",
        "5319e7",
        "--force",
        "--description",
        f"Bot-managed {family} review issue",
    )
    parent_body = _body_file(
        _manifest_path(root, args.parent_body), family=family, candidate_id="", surface="parent"
    )
    parent = _upsert(args.parent_title, label, parent_body)
    native = json.loads(
        _gh("issue", "view", parent, "--json", "subIssues", "--jq", "[.subIssues.nodes[].number]")
    )
    published = 0
    for row in children:
        candidate_id = str(
            row.get(args.id_key) or row.get("candidate_id") or row.get("sample_id") or ""
        )
        if not candidate_id:
            raise ValueError("review child is missing its candidate identity")
        title = str(row.get("title") or args.child_title.format(candidate_id=candidate_id))
        body = _body_file(
            _manifest_path(root, str(row["body_file"])),
            family=family,
            candidate_id=candidate_id,
            surface="child",
        )
        child = _upsert(title, label, body)
        if int(child) not in native:
            _gh("issue", "edit", parent, "--add-sub-issue", child)
            native.append(int(child))
        published += 1
    if published != len(children):
        raise RuntimeError("selected review children were not all published")
    print(
        publication_summary(
            status=PublicationStatus.PUBLISHED, selected=len(children), published=published
        )
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--family", required=True)
    parser.add_argument("--label", required=True)
    parser.add_argument("--parent-title", required=True)
    parser.add_argument("--parent-body", default="parent.md")
    parser.add_argument(
        "--child-title", required=True, help="Python format string with {candidate_id}"
    )
    parser.add_argument("--id-key", default="candidate_id")
    args = parser.parse_args(argv)
    return publish(args)


if __name__ == "__main__":
    raise SystemExit(main())
