slug: addison-tx-city-council
city: addison-tx
provider: swagit
meeting_family: council
source:
  list_url: https://addisontx.new.swagit.com/views/128
  body: "City Council"
  body_any:
    - "Work Session"
    - "Work Session and Regular Meeting"
    - "Special Meeting"
    - "Special Budget Meeting"
    - "Tax & Budget Public Hearing"
    - "Tax Rate Public Hearing"
    - "Budget Meeting"
    - "Combined Meeting"
    - "Special Council"
  body_includes:
    - provider_guid: "394474"
      body: "TIRZ #1 Board Meeting"
    - provider_guid: "311687"
      body: "Fiscal Year 2024-2025 Budget Workshop"
    - provider_guid: "297695"
      body: "Council Strategic Planning Day 1 & 2"
    - provider_guid: "268842"
      body: "Fiscal Year 2023-2024 Budget Workshop"
    - provider_guid: "268810"
      body: "Fiscal Year 2023-2024 Budget Workshop"
    - provider_guid: "55874"
      body: "Special Emergency Meeting"
podcast_title: "Addison: City Council"
podcast_author: "City of Addison, TX"
podcast_email: ""
podcast_description: "City Council meetings for Addison."
