slug: arlington-tx-environmental-task-force
city: arlington-tx
provider: granicus
source:
  feed_url: https://arlingtontx.granicus.com/ViewPublisherRSS.php?view_id=2&mode=vpodcast
  body_includes:
    - provider_guid: https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=3443
      body: Environmental Task Force
    - provider_guid: https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=3494
      body: Environmental Task Force Meeting
    - provider_guid: https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=3454
      body: Environmental Task Force Meeting
    - provider_guid: https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=3424
      body: Environmental Task Force Meeting
    - provider_guid: https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=3508
      body: Environmental Task Force Meeting
    - provider_guid: https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=3479
      body: Environmental Task Force Meeting
podcast_title: 'Arlington: Environmental Task Force'
podcast_author: City of Arlington, TX
podcast_email: ''
podcast_description: Verified 2020 Arlington Environmental Task Force proceedings.
