slug: arlington-tx-council
city: arlington-tx
provider: granicus
meeting_family: council
source:
  feed_url: https://arlingtontx.granicus.com/ViewPublisherRSS.php?view_id=2&mode=vpodcast
  body: "Council"
  body_any:
    - "Budget Town Hall Meeting"
    - "Special and Budget Town Hall Meeting"
    - "Special Meeting and Budget Town Hall Meeting"
    - "Community and Neighborhood Development Committee"
    - "Environmental Task Force"
    - "Evening Meeting"
    - "Afternoon Meeting"
    - "Special Meeting"
    - "Special Meeting - Evening"
    - "Special Meeting - Afternoon"
    - "Special Evening Meeting"
    - "Special Meeting - Canvassing"
    - "Special Afternoon Meeting"
  body_includes:
    - provider_guid: "https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=4890"
      body: "Special Joint Meeting"
    - provider_guid: "https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=3622"
      body: "Virtual Town Hall on Future Active Adult Center"
    - provider_guid: "https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=648"
      body: "Special Meeting-Phase I Gas Well Report"
    - provider_guid: "https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=484"
      body: "Special Meeting-Budget"
    - provider_guid: "https://arlingtontx.granicus.com/MediaPlayer.php?view_id=2&clip_id=232"
      body: "Special Meeting and District 5 Town Hall"
podcast_title: "Arlington: Council"
podcast_author: "City of Arlington, TX"
podcast_email: ""
podcast_description: "Council meetings for Arlington."
