slug: dallas-tx-economic-development
city: dallas-tx
provider: swagit
source:
  list_url: https://dallastx.new.swagit.com/views/113/city-council
  body: "Economic Development"
  body_includes:
    - provider_guid: "202470"
      body: "Reinvestment Zone 5 City Center"
    - provider_guid: "205545"
      body: "Small Business Resource Virtual Town Hall Meeting"
    - provider_guid: "204708"
      body: "Dallas City Center TIF District Board of Directors Meeting"
    - provider_guid: "204707"
      body: "Reinvestment Zone 10 Board Southwest Medical TIF"
    - provider_guid: "204701"
      body: "Joint Reinvestment Zone 05 (City Center) and Reinvestment Zone 11 (Downtown Connection) Boards"
    - provider_guid: "204697"
      body: "Reinvestment Zone 13 Board TIF Grand Park South"
    - provider_guid: "204694"
      body: "Reinvestment Zone 10 Board Southwest Medical"
    - provider_guid: "204691"
      body: "Reinvestment Zone 05 Board City Center"
    - provider_guid: "204687"
      body: "Reinvestment Zone 19 Board Cypress Waters"
    - provider_guid: "204683"
      body: "Reinvestment Zone 9 Board Vickery Meadow"
podcast_title: "Dallas: Economic Development"
podcast_author: "City of Dallas, TX"
podcast_email: ""
podcast_description: "Economic Development meetings for Dallas."
