slug: dallas-tx-mobility-solutions-infrastructure-and-sustainability-committee
city: dallas-tx
provider: swagit
source:
  list_url: https://dallastx.new.swagit.com/views/113/city-council
  body: 'Mobility Solutions, Infrastructure and Sustainability Committee'
podcast_title: 'Dallas: Mobility Solutions, Infrastructure and Sustainability Committee'
podcast_author: 'City of Dallas, TX'
podcast_email: ''
podcast_description: 'Mobility Solutions, Infrastructure and Sustainability Committee meetings for Dallas, TX.'
