slug: dallas-tx-bid-purchasing
city: dallas-tx
provider: swagit
source:
  list_url: https://dallastx.new.swagit.com/views/113/city-council
  body: "Bid Purchasing"
  body_includes:
    - provider_guid: "205111"
      body: "Purchasing Bids 7-30-2015"
    - provider_guid: "205110"
      body: "Purchasing Bids 7-23-2015"
    - provider_guid: "205097"
      body: "Purchasing Bids 4-23-2015"
    - provider_guid: "205096"
      body: "Purchasing Bids 4-16-2015"
    - provider_guid: "205095"
      body: "Purchasing Bids 4-9-2015"
    - provider_guid: "205094"
      body: "Purchasing Bids 4-2-2015"
    - provider_guid: "205093"
      body: "Purchasing Bids 3-26-2015"
    - provider_guid: "205092"
      body: "Purchasing Bids 3-19-2015"
    - provider_guid: "205091"
      body: "Purchasing Bids 3-12-2015"
    - provider_guid: "205090"
      body: "Purchasing Bids 3-5-2015"
    - provider_guid: "205089"
      body: "Purchasing Bids 2-26-2015"
    - provider_guid: "205088"
      body: "Purchasing Bids 2-20-2015"
    - provider_guid: "205087"
      body: "Purchasing Bids 2-19-2015"
    - provider_guid: "205086"
      body: "Purchasing Bids 2-12-2015"
    - provider_guid: "205085"
      body: "Purchasing Bids 2-5-2015"
    - provider_guid: "205084"
      body: "Purchasing Bids 1-29-2015"
    - provider_guid: "205083"
      body: "Purchasing Bids 1-22-2015"
    - provider_guid: "205082"
      body: "Purchasing Bids 1-15-2015"
    - provider_guid: "205081"
      body: "Purchasing Bids 1-8-2015"
    - provider_guid: "205080"
      body: "Purchasing Bids 12-18-2014"
    - provider_guid: "205079"
      body: "Purchasing Bids 12-11-2014"
    - provider_guid: "205078"
      body: "Purchasing Bids 12-4-2014"
    - provider_guid: "205077"
      body: "Purchasing Bids 11-20-2014"
    - provider_guid: "205076"
      body: "Purchasing Bids 11-13-2014"
    - provider_guid: "205075"
      body: "Purchasing Bids 11-6-2014"
    - provider_guid: "205074"
      body: "Purchasing Bids 10-30-2014"
    - provider_guid: "205049"
      body: "Purchasing Bids 5-8-2014"
    - provider_guid: "205048"
      body: "Purchasing Bids 5-1-2014"
    - provider_guid: "205047"
      body: "Purchasing Bids 4-24-2014"
    - provider_guid: "205046"
      body: "Purchasing Bids 4-17-2014"
    - provider_guid: "205045"
      body: "Purchasing Bids 4-10-2014"
    - provider_guid: "205044"
      body: "Purchasing Bids 4-3-2014"
    - provider_guid: "205043"
      body: "Purchasing Bids 3-27-2014"
    - provider_guid: "205042"
      body: "Purchasing Bids 3-20-2014"
    - provider_guid: "205041"
      body: "Purchasing Bids 3-13-2014"
    - provider_guid: "205040"
      body: "Purchasing Bids 3-6-2014"
    - provider_guid: "205039"
      body: "Purchasing Bids 2-27-2014"
    - provider_guid: "205038"
      body: "Purchasing Bids 2-20-2014"
    - provider_guid: "205013"
      body: "Purchasing Bids 8-8-2013"
    - provider_guid: "205012"
      body: "Purchasing Bids 8-1-2013"
    - provider_guid: "205011"
      body: "Purchasing Bids 7-25-2013"
    - provider_guid: "205010"
      body: "Purchasing Bids 7-18-2013"
    - provider_guid: "205009"
      body: "Purchasing Bids 7-11-2013"
    - provider_guid: "205008"
      body: "Purchasing Bids 6-27-2013"
    - provider_guid: "205007"
      body: "Purchasing Bids 6-20-2013"
    - provider_guid: "205006"
      body: "Purchasing Bids 6-13-2013"
    - provider_guid: "205005"
      body: "Purchasing Bids 6-10-2013"
    - provider_guid: "205004"
      body: "Purchasing Bids 6-6-2013"
    - provider_guid: "205003"
      body: "Purchasing Bids 5-30-2013"
    - provider_guid: "205002"
      body: "Purchasing Bids 5-23-2013"
    - provider_guid: "205506"
      body: "Mill Creek Tunnel Pre-Bid Meeting"
  body_any:
    - "Purchasing Bids 7-16-2015"
    - "Purchasing Bids 7-9-2015"
    - "Purchasing Bids 7-2-2015"
    - "Purchasing Bids 6-25-2015"
    - "Purchasing Bids 6-18-2015"
    - "Purchasing Bids 6-11-2015"
    - "Purchasing Bids 6-4-2015"
    - "Purchasing Bids 5-28-2015"
    - "Purchasing Bids 5-21-2015"
    - "Purchasing Bids 5-14-2015"
    - "Purchasing Bids 5-7-2015"
    - "Purchasing Bids 4-30-2015"
    - "Purchasing Bids 10-23-2014"
    - "Purchasing Bids 10-16-2014"
    - "Purchasing Bids 10-9-2014"
    - "Purchasing Bids 10-2-2014"
    - "Purchasing Bids 9-25-2014"
    - "Purchasing Bids 9-18-2014"
    - "Purchasing Bids 9-11-2014"
    - "Purchasing Bids 9-4-2014"
    - "Purchasing Bids 8-28-2014"
    - "Purchasing Bids 8-21-2014"
    - "Purchasing Bids 8-14-2014"
    - "Purchasing Bids 8-7-2014"
    - "Purchasing Bids 7-31-2014"
    - "Purchasing Bids 7-24-2014"
    - "Purchasing Bids 7-17-14"
    - "Purchasing Bids 7-10-14"
    - "Purchasing Bids 7-3-14"
    - "Purchasing Bids 6-26-2014"
    - "Purchasing Bids 6-19-2014"
    - "Purchasing Bids 6-12-2014"
    - "Purchasing Bids 6-5-2014"
    - "Purchasing Bids 5-29-2014"
    - "Purchasing Bids 5-22-2014"
    - "Purchasing Bids 5-15-2014"
    - "Purchasing Bids 2-13-2014"
    - "Purchasing Bids 2-6-2014"
    - "Purchasing Bids 1-30-2014"
    - "Purchasing Bids 1-23-2014"
    - "Purchasing Bids 1-16-2014"
    - "Purchasing Bids 1-9-2014"
    - "Purchasing Bids 12-19-2013"
    - "Purchasing Bids 12-12-2013"
    - "Purchasing Bids 12-05-2013"
    - "Purchasing Bids 11-21-2013"
    - "Purchasing Bids 11-14-2013"
    - "Purchasing Bids 11-07-2013"
    - "Purchasing Bids 10-30-2013"
    - "Purchasing Bids 10-24-2013"
    - "Purchasing Bids 10-17-2013"
    - "Purchasing Bids 10-10-2013"
    - "Purchasing Bids 10-3-2013"
    - "Purchasing Bids 9-26-2013"
    - "Purchasing Bids 9-19-2013"
    - "Purchasing Bids 9-12-2013"
    - "Purchasing Bids 9-5-2013"
    - "Purchasing Bids 8-29-2013"
    - "Purchasing Bids 8-22-2013"
    - "Purchasing Bids 8-15-2013"
    - "Purchasing Bids 5-16-2013"
    - "Purchasing Bids 5-9-2013"
    - "Purchasing Bids 5-2-2013"
    - "Purchasing Bids 4-25-2013"
    - "Purchasing Bids 4-18-2013"
    - "Purchasing Bids 4-11-2013"
    - "Purchasing Bids_4-4-2013"
    - "Purchasing Bids 3-28-2013"
    - "Purchasing Bids 3-21-2013"
    - "Purchasing Bids 3-14-2013"
    - "Purchasing Bids 3-7-2013"
    - "Purchasing Bids 2-28-2013"
    - "Purchasing Bids 2-21-2013"
    - "Purchasing Bids 2-14-2013"
    - "Purchasing Bids 2-7-2013"
    - "Purchasing Bids 1-31-2013"
    - "Purchasing Bids 1-24-2013"
    - "Purchasing Bids 1-17-2013"
    - "Purchasing Bids 1-10-2013"
    - "Purchasing Bids 1-3-2013"
    - "Purchasing Bids 12-20-2012"
    - "Purchasing Bids 12-13-2012"
    - "Purchasing Bids 12-6-2012"
    - "Purchasing Bids 11-29-2012"
podcast_title: "Dallas: Bid Purchasing"
podcast_author: "City of Dallas, TX"
podcast_email: ""
podcast_description: "Bid Purchasing meetings for Dallas."
