slug: dallas-tx-economic-development
city: dallas-tx
provider: swagit
source:
  list_url: https://dallastx.new.swagit.com/views/113/city-council
  body: "Economic Development"
podcast_title: "Dallas: Economic Development"
podcast_author: "City of Dallas, TX"
podcast_email: ""
podcast_description: "Economic Development meetings for Dallas."
