slug: dallas-tx-economic-development
city: dallas-tx
provider: swagit
source:
  list_url: https://dallastx.new.swagit.com/views/113/city-council
  body: "Economic Development"
  body_includes:
    - provider_guid: "203327"
      body: "Dallas Development Fund"
    - provider_guid: "204776"
      body: "Downtown Connection TIF Meeting"
    - provider_guid: "204775"
      body: "Reinvestment Zone 06 Board Grand Park South"
    - provider_guid: "204773"
      body: "Reinvestment Zone 06 Board Farmers Market"
    - provider_guid: "204772"
      body: "Reinvestment Zone 06 Board Farmers Market"
    - provider_guid: "204724"
      body: "Reinvestment Zone 06 Board Farmers Market"
    - provider_guid: "203311"
      body: "Reinvestment Zone 06 Board Farmers Market"
    - provider_guid: "204770"
      body: "Reinvestment Zone 10 Board Southwestern Medical"
    - provider_guid: "204731"
      body: "Reinvestment Zone 10 Board Southwestern Medical"
    - provider_guid: "204715"
      body: "Reinvestment Zone 10 Board Southwestern Medical"
    - provider_guid: "204690"
      body: "Reinvestment Zone 10 Board Southwestern Medical"
    - provider_guid: "204769"
      body: "Mall Area Redevelopment TIF District--Special Called Meeting"
    - provider_guid: "204766"
      body: "Dallas TOD TIF District Board of Directors Meeting"
    - provider_guid: "204755"
      body: "Dallas TOD TIF District Board of Directors Meeting"
    - provider_guid: "204691"
      body: "Reinvestment Zone 05 Board City Center"
    - provider_guid: "204687"
      body: "Reinvestment Zone 19 Board Cypress Waters"
    - provider_guid: "204683"
      body: "Reinvestment Zone 9 Board Vickery Meadow"
    - provider_guid: "204682"
      body: "Reinvestment Zone 5: City Center & Reinvestment Zone 11: Downtown Connection TIF"
    - provider_guid: "204679"
      body: "Reinvestment Zone Six Farmers Market TIF"
    - provider_guid: "204680"
      body: "Reinvestment Zone 17: TOD TIF"
    - provider_guid: "204678"
      body: "Reinvestment Zone 12: Deep Ellum TIF"
    - provider_guid: "204675"
      body: "Dallas Joint Board of Directors Reinvestment Zone 05 & 11"
    - provider_guid: "204660"
      body: "Dallas Joint Board of Directors Reinvestment Zone 05 & 11"
    - provider_guid: "204648"
      body: "Dallas Joint Board of Directors Reinvestment Zone 05 & 11"
    - provider_guid: "204641"
      body: "Dallas Joint Board of Directors Reinvestment Zone 05 & 11"
    - provider_guid: "204672"
      body: "Reinvestment Zone 20 Mall Area Redevelopment"
    - provider_guid: "204671"
      body: "Reinvestment Zone 20 Mall Area Redevelopment"
    - provider_guid: "204665"
      body: "Reinvestment Zone 20 Mall Area Redevelopment"
    - provider_guid: "272227"
      body: "2024 Bond Critical Facilities Subcommittee"
    - provider_guid: "270972"
      body: "2024 Bond Critical Facilities Subcommittee"
    - provider_guid: "272231"
      body: "2024 Bond ECO, HOU, OHS Meeting"
    - provider_guid: "233039"
      body: "2024 Bond ECO, HOU, OHS Meeting"
    - provider_guid: "230800"
      body: "2024 Bond ECO, HOU, OHS Meeting"
    - provider_guid: "269916"
      body: "2024 Capital Bond CBTF Meeting"
    - provider_guid: "269278"
      body: "2024 Capital Bond CBTF Meeting"
    - provider_guid: "246971"
      body: "2024 Capital Bond CBTF Meeting"
    - provider_guid: "259822"
      body: "2024 Capital Bond CBTF Meeting"
    - provider_guid: "233037"
      body: "2024 Capital Bond CBTF Meeting"
    - provider_guid: "270973"
      body: "2024 Bond ECONOM"
    - provider_guid: "269608"
      body: "2024 Bond Task Force Community Bond Task Force Meeting"
    - provider_guid: "269611"
      body: "2024 Bond Task Force Critical Facilities Subcommittee Meeting"
    - provider_guid: "268088"
      body: "2024 Bond Program: Allocation Discussion"
    - provider_guid: "259828"
      body: "2024 Capital Bond ECONOM Meeting"
    - provider_guid: "259831"
      body: "2024 Capital Bond ECONOM Meeting"
    - provider_guid: "205483"
      body: "Grow South 2:  Mayor Rawlings’ Vision for Southern Dallas"
podcast_title: "Dallas: Economic Development"
podcast_author: "City of Dallas, TX"
podcast_email: ""
podcast_description: "Economic Development meetings for Dallas."
