slug: denton-tx-committee-on-the-environment
city: denton-tx
provider: swagit
source:
  list_url: https://dentontx.new.swagit.com/views/5
  body: 'Committee on the Environment'
podcast_title: 'Denton: Committee on the Environment'
podcast_author: 'City of Denton, TX'
podcast_email: ''
podcast_description: 'Committee on the Environment meetings for Denton, TX.'
