slug: denton-tx-city-council
city: denton-tx
provider: swagit
meeting_family: council
source:
  list_url: https://dentontx.new.swagit.com/views/5
  body: "City Council"
  body_exact:
    - Joint Luncheon with Library Board
  body_includes:
    - provider_guid: "112591"
      body: "Denton State of the City"
    - provider_guid: "13109"
      body: "2nd Tuesday Session"
    - provider_guid: "13733"
      body: "Managing Gas Well Emergencies"
    - provider_guid: "13718"
      body: "Gas Well Ordinance Discussion"
    - provider_guid: "385753"
      body: "Hotel Occupancy Tax Workshop"
    - provider_guid: "357498"
      body: "Missing Middle Housing"
    - provider_guid: "353205"
      body: "Denton Finance End-of-Year"
    - provider_guid: "301930"
      body: "Lily Cantu Inclusive Playground"
    - provider_guid: "301511"
      body: "Mayhill Road Name Change"
    - provider_guid: "272798"
      body: "Joe Skiles Park Renovation"
    - provider_guid: "208991"
      body: "Joe Skiles Park Renovation"
    - provider_guid: "271071"
      body: "Virtual Community Meeting - Aquatic Master Plan"
    - provider_guid: "263945"
      body: "2019 Bond Neighborhood 4"
    - provider_guid: "223742"
      body: "Neighborhood 1A Construction Kickoff"
    - provider_guid: "209439"
      body: "Virtual Community Meeting - Neighborhood 7A"
    - provider_guid: "208992"
      body: "Denia Park Renovation"
    - provider_guid: "190454"
      body: "Quakertown Memorialization"
    - provider_guid: "189893"
      body: "Quakertown Memorialization"
    - provider_guid: "208162"
      body: "Virtual Community Meeting - Roberts Addition"
    - provider_guid: "189918"
      body: "Street Sign Topper Program"
    - provider_guid: "179856"
      body: "Virtual Community Meeting - Briercliff Park Master Plan"
    - provider_guid: "44214"
      body: "Denton Police Press Conference Tarver Shooting"
podcast_title: "Denton: City Council"
podcast_author: "City of Denton, TX"
podcast_email: ""
podcast_description: "City Council meetings for Denton."
