slug: fort-worth-tx-city-council
city: fort-worth-tx
provider: granicus
meeting_family: council
source:
  feed_urls: ['https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=5&mode=vpodcast', 'https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=9&mode=vpodcast', 'https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=10&mode=vpodcast', 'https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=11&mode=vpodcast', 'https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=12&mode=vpodcast']
  body: "City Council"
  body_includes:
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=5&clip_id=6331"
      body: "Work Session"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=9&clip_id=6331"
      body: "Work Session"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=5&clip_id=6334"
      body: "Budget Work Session Budget Work Session"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=9&clip_id=6334"
      body: "Budget Work Session Budget Work Session"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6207"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6206"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6205"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6185"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6177"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6207"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6206"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6205"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6185"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6177"
      body: "2026 Bond & Charter Public Education Meeting 2026 Bond & Charter Public Education Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6157"
      body: "The Mayor's Neighborhood Awards The Mayor's Neighborhood Awards"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6157"
      body: "The Mayor's Neighborhood Awards The Mayor's Neighborhood Awards"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6080"
      body: "Cold Weather Update Press Conference Cold Weather Update Press Conference"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6080"
      body: "Cold Weather Update Press Conference Cold Weather Update Press Conference"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6026"
      body: "Help Build Our Future District 10 Bond Meeting Help Build Our Future District 10 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6026"
      body: "Help Build Our Future District 10 Bond Meeting Help Build Our Future District 10 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6020"
      body: "Help Build Our Future District 5 Bond Meeting Help Build Our Future District 5 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6020"
      body: "Help Build Our Future District 5 Bond Meeting Help Build Our Future District 5 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6019"
      body: "Help Build Our Future District 6 Bond Meeting Help Build Our Future District 6 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6019"
      body: "Help Build Our Future District 6 Bond Meeting Help Build Our Future District 6 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6018"
      body: "Help Build Our Future District 2 Bond Meeting Help Build Our Future District 2 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6018"
      body: "Help Build Our Future District 2 Bond Meeting Help Build Our Future District 2 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6014"
      body: "Help Build Our Future District 9 Bond Meeting Help Build Our Future District 9 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6014"
      body: "Help Build Our Future District 9 Bond Meeting Help Build Our Future District 9 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6013"
      body: "Help Build Our Future District 11 Bond Meeting Help Build Our Future District 11 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6013"
      body: "Help Build Our Future District 11 Bond Meeting Help Build Our Future District 11 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6008"
      body: "Help Build Our Future District 3 Bond Meeting Help Build Our Future District 3 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6008"
      body: "Help Build Our Future District 3 Bond Meeting Help Build Our Future District 3 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6002"
      body: "Help Build Our Future District 4 Bond Meeting Help Build Our Future District 4 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6002"
      body: "Help Build Our Future District 4 Bond Meeting Help Build Our Future District 4 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6000"
      body: "Help Build Our Future District 8 Bond Meeting Help Build Our Future District 8 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=6000"
      body: "Help Build Our Future District 8 Bond Meeting Help Build Our Future District 8 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5992"
      body: "Help Build Our Future District 7 Bond Meeting Help Build Our Future District 7 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=5992"
      body: "Help Build Our Future District 7 Bond Meeting Help Build Our Future District 7 Bond Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5988"
      body: "State of the City 2025 State of the City 2025"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=5988"
      body: "State of the City 2025 State of the City 2025"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5987"
      body: "Fort Worth Business Plan Competition Finals | October 14, 2025 Fort Worth Business Plan Competition Finals | October 14, 2025"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=5987"
      body: "Fort Worth Business Plan Competition Finals | October 14, 2025 Fort Worth Business Plan Competition Finals | October 14, 2025"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5971"
      body: "Future Downtown Library Community Report Future Downtown Library Community Report"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=5971"
      body: "Future Downtown Library Community Report Future Downtown Library Community Report"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5950"
      body: "District 8 Budget Meeting District 8 Budget Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=5950"
      body: "District 8 Budget Meeting District 8 Budget Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5948"
      body: "District 2 Budget Meeting District 2 Budget Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=5948"
      body: "District 2 Budget Meeting District 2 Budget Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5947"
      body: "District 5 Budget Meeting District 5 Budget Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=12&clip_id=5947"
      body: "District 5 Budget Meeting District 5 Budget Meeting"
  body_any:
    - "Special Called Meeting To Canvass Election Results of May 17, 2022 Special Called Meeting To Canvass Election Results of May 17, 2022"
    - "Special Council Meeting of April 20, 2022 Special Council Meeting of April 20, 2022"
    - "Special Called Meeting to Draw and Submit a Proposed Ten-District Map to the Redistricting Task Force Special Called Meeting to Draw and Submit a Proposed Ten-District Map to the Redistricting Task Force"
    - "Special Called Joint Meeting With Redistricting Task Force Special Called Joint Meeting With Redistricting Task Force"
    - "Council Retreat Council Retreat"
    - "SPECIAL CALLED MEETING AND PRE-COUNCIL MEETING SPECIAL CALLED MEETING AND PRE-COUNCIL MEETING"
    - "SWEARING IN CEREMONY SWEARING IN CEREMONY"
    - "Special Called Meeting Special Called Meeting"
    - "Called Special Meeting Called Special Meeting"
podcast_title: "Fort Worth: City Council"
podcast_author: "City of Fort Worth, TX"
podcast_email: ""
podcast_description: "City Council meetings for Fort Worth."
