slug: fort-worth-tx-downtown-design-and-review-board
city: fort-worth-tx
provider: granicus
source:
  feed_urls: ['https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=5&mode=vpodcast', 'https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=9&mode=vpodcast', 'https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=10&mode=vpodcast', 'https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=11&mode=vpodcast', 'https://fortworthgov.granicus.com/ViewPublisherRSS.php?view_id=12&mode=vpodcast']
  body: "Downtown Design and Review Board"
  body_any:
    - "Downtown Design Review Board Downtown Design Review Board"
    - "March 6, DDRB March 6, DDRB"
    - "February 6, DDRB February 6, DDRB"
    - "December 5, DDRB Meeting December 5, DDRB Meeting"
    - "September Downtown Design Review Board September Downtown Design Review Board"
    - "March Downtown Design Review Board March Downtown Design Review Board"
    - "February Downtown Design Review Board February Downtown Design Review Board"
    - "April Downtown Design Review Board April Downtown Design Review Board"
    - "August Downtown Design Review Board August Downtown Design Review Board"
    - "December Downtown Design Review Board December Downtown Design Review Board"
    - "November 9, DDRB Meeting November 9, DDRB Meeting"
    - "June Downtown Design Review Board June Downtown Design Review Board"
    - "May Downtown Design Review Board May Downtown Design Review Board"
  body_includes:
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=6049"
      body: "December DDRB December DDRB"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=11&clip_id=6049"
      body: "December DDRB December DDRB"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5833"
      body: "June 5, DDRB Meeting June 5, DDRB Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=11&clip_id=5833"
      body: "June 5, DDRB Meeting June 5, DDRB Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=10&clip_id=5800"
      body: "May 1, DDRB Meeting May 1, DDRB Meeting"
    - provider_guid: "https://fortworthgov.granicus.com/MediaPlayer.php?view_id=11&clip_id=5800"
      body: "May 1, DDRB Meeting May 1, DDRB Meeting"
podcast_title: "Fort Worth: Downtown Design and Review Board"
podcast_author: "City of Fort Worth, TX"
podcast_email: ""
podcast_description: "Downtown Design and Review Board meetings for Fort Worth."
